-- Run this in Supabase SQL Editor to enforce New Lead Management Highlighting System
ALTER TABLE leads ADD COLUMN IF NOT EXISTS is_new BOOLEAN DEFAULT TRUE;
ALTER TABLE demo_bookings ADD COLUMN IF NOT EXISTS is_new BOOLEAN DEFAULT TRUE;
ALTER TABLE counselling_requests ADD COLUMN IF NOT EXISTS is_new BOOLEAN DEFAULT TRUE;
ALTER TABLE reported_tutors ADD COLUMN IF NOT EXISTS is_new BOOLEAN DEFAULT TRUE;
ALTER TABLE contact_messages ADD COLUMN IF NOT EXISTS is_new BOOLEAN DEFAULT TRUE;
ALTER TABLE tutor_registrations ADD COLUMN IF NOT EXISTS is_new BOOLEAN DEFAULT TRUE;
